authorName: unknown
experimentName: SPOS Search
trialConcurrency: 1
maxExecDuration: 7d
maxTrialNum: 99999
trainingServicePlatform: local
searchSpacePath: nni_auto_gen_search_space.json
useAnnotation: false
#tuner:
#  codeDir: .
#  classFileName: tuner.py
#  className: EvolutionWithFlops
#tuner:
#  builtinTunerName: PPOTuner
#  classArgs:
#    optimize_mode: maximize

tuner:
  codeDir: .
  classFileName: random_nas_tuner.py
  className: RandomNASTuner
trial:
  command: python tester_cifar.py
  codeDir: .
  gpuNum: 1
